name: Traffic Data Collector

on:
  schedule:
    # 14:00 UTC is 7 AM PDT (Aiming for an 8 AM actual start)
    # 18:00 UTC is 11 AM PDT (Aiming for a 12 PM actual start)
    # 23:00 UTC is 4 PM PDT (Aiming for a 5 PM actual start)
    - cron: '0 14,18,23 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run collection script
        run: python collect.py

      - name: Save images to repo
        run: |
          git config --global user.name "TrafficBot"
          git config --global user.email "bot@github.com"
          git add *.jpg
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated Traffic Capture"
          git push
